name: "first workflow"
on: 
  push:
  pull_request:
    branches:
      - main
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: 24
                cache: "npm"

            - name: install dependency
              run: npm ci

            - name: run ESLint in code
              run: npm run lint

            - name: run test cases
              run: npm run test

            - name: make react build
              run: npm run build

            - name: create-artifacts
              uses: actions/upload-artifact@v4
              with:
                name: react-artifacts
                path: dist/
                retention-days: 7

